# Файл: Dockerfile.bot

FROM python:3.12-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код бота
COPY dtek_telegram_bot.py .

# Запуск скрипта бота
CMD ["python", "dtek_telegram_bot.py"]