# Файл: Dockerfile.parser

# Обновление до версии 1.55.0 (соответствует требованиям Playwright)
FROM mcr.microsoft.com/playwright/python:v1.55.0-jammy 

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код API и парсеры
COPY api.py .
COPY dtek/ ./dtek/
COPY cek/ ./cek/

# Запуск Uvicorn (FastAPI)
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]