# Файл: Dockerfile.parser

# Обновление до версии 1.55.0 (соответствует требованиям Playwright)
FROM mcr.microsoft.com/playwright/python:v1.55.0-jammy 

WORKDIR /apps

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код API и парсера
COPY dtek_parser_api.py .
COPY dtek_parser.py .
COPY security_middleware.py .

# Запуск Uvicorn (FastAPI)
CMD ["uvicorn", "dtek_parser_api:app", "--host", "0.0.0.0", "--port", "8000"]